version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
  web:
    build: .
    environment:
      - DB_NAME=dev
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=test
      - DB_PASSWORD=test123
      - DJANGO_SECRET_KEY=dac07428-6937-485a-9ad7-25ac9559a36c
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./src/:/opt/app/
    ports:
      - "8080:8080"
    depends_on:
      - db
