version: '2.2'

services:
  script_service:
    build: services/script_service/.
    restart: on-failure
    depends_on:
      broker:
        condition: service_healthy
  broker:
    build: broker/.
    environment:
      - RABBITMQ_ERLANG_COOKIE='test'
      - RABBITMQ_NODENAME=rabbit@localhost
    ports:
      - 8080:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
