version: '3'

services:
  broker:
    image: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE='test'
      - RABBITMQ_NODENAME=rabbit@localhost
    ports:
      - 8080:15672
  script_service:
    build: services/script_service/.
    
