version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=DB_NAME
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASSWORD
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./src/:/opt/app/
    ports:
      - "8080:8080"
    depends_on:
      - db
