# Generated by Django 3.0.8 on 2020-07-27 01:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script_file', models.FileField(unique=True, upload_to='scripts/')),
                ('revision', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['revision', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('file_type', models.CharField(choices=[('bash', 'Borne Again Shell Script'), ('py', 'Python Script'), ('sh', 'Shell Script'), ('yaml', 'YAML')], max_length=5)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='script_manager.ScriptRevision')),
            ],
            options={
                'ordering': ['name', 'last_change'],
            },
        ),
    ]
