# Generated by Django 3.1.2 on 2020-10-06 03:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_url', models.CharField(max_length=128, unique=True)),
                ('version', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['version', 'creation_date', 'last_date_modified', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScriptExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script_to_execute', models.CharField(max_length=128)),
                ('arguments', models.CharField(max_length=128)),
                ('git_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script_manager.gitrepo')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('last_date_modified', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script_manager.gitrepo')),
            ],
            options={
                'ordering': ['name', 'last_date_modified', 'creation_date'],
            },
        ),
    ]
