# Generated by Django 3.1.1 on 2020-09-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptrevision',
            name='script_file',
            field=models.URLField(),
        ),
    ]
